Repository New-Barams/this-year-ajaja-fe, pull requests merged in 2023-12, with the labels that each got.

#243 README 작성 main branch 반영
  README.md
Labels: 🚨긴급

#249 [민우] - Dropdown 컴포넌트 수정
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
Labels: 🚨긴급

#253 [혜수] - 외부 레이아웃 디자인 변경(위치만 잡아놓기)
  src/app/(headerless)/login/index.scss
  src/app/index.scss
  src/app/layout.tsx
  src/styles/origin-theme.scss
  src/styles/standard.scss
  src/styles/themes.scss
Labels: 🚨긴급

#250 [노철] - 공용 컴포넌트 변경
  src/components/IconSwitchButton/IconSwitchButton.tsx
  src/components/IconSwitchButton/index.scss
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/SwitchButton/index.scss
  src/components/Tag/Tag.tsx
  src/components/Tag/index.scss
Labels: 🚨긴급

#255 [민우] - planInput, remindInput 컴포넌트 수정
  src/components/PlanInput/PlanInput.tsx
  src/components/PlanInput/index.scss
  src/components/RemindInput/RemindInput.tsx
  src/components/RemindInput/index.scss
Labels: 🚨긴급

#257 [혜수] - 공통 컴포넌트 변경(아좌좌 버튼, 일반 버튼)
  src/app/index.scss
  src/app/layout.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/AjajaButton/index.scss
  src/components/Button/Button.tsx
  src/components/Button/index.scss
  src/styles/class/font-size.scss
  src/styles/font.scss
  src/styles/reset.scss
  src/types/Color.ts
Labels: 🚨긴급

#258 [노철] - 토큰 갱신 로직 추가
  src/apis/axiosInstanceClient.ts
  src/apis/client/postReissue.ts
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/constants/api.ts
  src/types/apis/ErrorResponseData.ts
  src/utils/checkTokenExp.ts
  src/utils/decodeJWT.ts
Labels: 🚨긴급

#263 [혜수] - 네비게이션바 추가
  src/app/(header)/my/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/app/_components/Navigation/index.scss
  src/app/_components/index.scss
  src/app/layout.tsx
  src/components/Icon/Icon.tsx
  src/types/IconName.ts
Labels: 🚨긴급

#268 [노철] - 토큰 재발행 에러 추가
  src/apis/axiosInstanceClient.ts
Labels: 🚨긴급, 🐛버그

#265 [노철] - 로그인페이지
  package-lock.json
  package.json
  public/loginPage/first.png
  public/loginPage/fourth.png
  public/loginPage/kakao_login_large_narrow.png
  public/loginPage/kakao_login_large_wide.png
  public/loginPage/second.png
  public/loginPage/third.png
  public/loginPage/this-year-ajaja-logo-text.svg
  src/app/(headerless)/login/_components/IntroduceSwiper/IntroduceSwiper.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
Labels: 🚨긴급

#270 [노철] - axios interceptor 에러 수정
  src/apis/axiosInstanceClient.ts
Labels: 🚨긴급, 🐛버그

#273 [노철] - build 에러 제거
  src/components/WritablePlan/WritablePlan.tsx
Labels: 🚨긴급, 🐛버그

#274 [혜수] - 랜딩페이지 작성
  public/github.svg
  public/notion.svg
  public/this-year-ajaja-logo-flat.svg
  src/app/(header)/layout.tsx
  src/app/_components/LandingPage/LandingPage.tsx
  src/app/_components/LandingPage/index.scss
  src/app/layout.tsx
Labels: 🚨긴급

#277 [혜수] - 홈 페이지 수정
  public/animal/alpaca.png
  public/animal/bear.png
  public/animal/cat.png
  public/animal/cow.png
  public/animal/dog.png
  public/animal/frog.png
  public/animal/lion.png
  public/animal/mouse.png
  public/animal/panda.png
  public/animal/penguin.png
  public/animal/pig.png
  public/animal/tiger.png
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
  src/app/(header)/home/_components/Plan/Plan.tsx
  src/app/(header)/home/_components/Plan/index.scss
  src/app/(header)/home/_components/ProgressBar/ProgressBar.tsx
  src/app/(header)/home/_components/ProgressBar/index.scss
  src/app/(header)/home/_components/index.scss
  src/app/(header)/home/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/components/Button/index.scss
  src/constants/planIcons.ts
  src/stores/canMakeNewPlanStore.ts
  src/styles/font.scss
  src/types/FontSize.ts
  src/types/PlanIconName.ts
  src/types/index.ts
Labels: 🚨긴급

#278 [노철] - 마이페이지 디자인 변경
  src/apis/axiosInstanceClient.ts
  src/apis/client/putUserReceive.ts
  src/app/(header)/my/_components/ModalRemindWay/ModalRemindWay.tsx
  src/app/(header)/my/_components/ModalRemindWay/index.scss
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/hooks/apis/usePutUserReceiveMutation.ts
  src/hooks/apis/useRefreshNicknameMutation.ts
  src/types/apis/users/GetUserInformation.ts
Labels: 🚨긴급

#281 [민우] - 계획 작성 페이지 분리 및 구현
  package-lock.json
  package.json
  src/app/(header)/create/_components/CreatePlanStepper/CreatePlanStepper.tsx
  src/app/(header)/create/_components/CreatePlanStepper/index.scss
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/app/(header)/create/_components/StepButtonGroup/index.scss
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/index.scss
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIcon/index.scss
  src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
  src/components/CreatePlanIconExample/index.scss
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindDate/index.scss
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
  src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
  src/components/ModalFixRemindDate/index.scss
  src/components/ModalSelectIcon/ModalSelectIcon.tsx
  src/components/ModalSelectIcon/index.scss
  src/components/PlanInput/PlanInput.tsx
  src/components/PlanInput/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/components/RemindItem/WritableRemindItem/index.scss
  src/components/index.ts
  src/constants/createPlanSessionKey.ts
  src/constants/createPlanStepTitle.ts
  src/constants/index.ts
  src/constants/remindOptions.ts
  src/hooks/apis/usePostNewPlanMutation.ts
  src/hooks/useSessionStorage.ts
  src/types/Plan.ts
  src/types/Remind.ts
  src/types/apis/remind/getRemind.ts
  src/utils/clearCreatePlanSessionData.ts
Labels: 🚨긴급

#283 [혜수] - 둘러보기 페이지 수정
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/app/(header)/explore/_components/Plans/index.scss
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/explore/_components/Tab/index.scss
  src/components/AjajaButton/AjajaButton.tsx
Labels: 🚨긴급

#286 [혜수] - 로고 파일 변경 & 파비콘 변경
  public/favicon.svg
  public/this-year-ajaja-logo-flat.svg
  public/this-year-ajaja-logo-old.svg
  public/this-year-ajaja-logo.svg
  src/app/_components/LandingPage/LandingPage.tsx
  src/app/_components/LandingPage/index.scss
  src/app/layout.tsx
Labels: 🎶낮음

#287 [노철] - 계획 상세페이지 리팩토링
  next.config.js
  public/kakaoShare.png
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/layout.tsx
  src/components/DebounceSwitchButton/DebounceSwitchButton.tsx
  src/components/DebounceSwitchButton/index.scss
  src/components/IconSwitchButton/IconSwitchButton.tsx
  src/components/KakaoShareButton/KakaoShareButton.tsx
  src/components/KakaoShareButton/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/ReadOnlyPlan/index.scss
  src/components/SwitchButton/index.scss
  src/types/apis/plan/GetPlan.ts
Labels: 🚨긴급

#289 [민우] - 리마인드 상세 페이지 수정
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/app/(header)/reminds/[planId]/error.tsx
  src/app/(header)/reminds/[planId]/index.scss
  src/app/(header)/reminds/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/error.tsx
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/DebounceSwitchButton/index.scss
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/ReadOnlyRemindItem/index.scss
  src/constants/remindTimeText.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/middleware.ts
  src/types/Remind.ts
Labels: 🚨긴급

#291 [혜수] - 스크롤 적용 위치 변경
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Tab/index.scss
  src/app/(header)/explore/_components/index.scss
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/index.scss
  src/styles/standard.scss
  src/styles/webkit.scss
Labels: 💡중간

#292 [노철] - 계획 수정페이지 디자인 변경
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/error.tsx
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/hooks/useWritablePlan.ts
  src/types/apis/plan/EditPlan.ts
Labels: 🚨긴급

#293 [민우] - 리마인드 수정 페이지
  src/apis/client/editRemind.ts
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/app/(header)/create/page.tsx
  src/app/(header)/reminds/[planId]/index.scss
  src/app/(header)/reminds/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/index.scss
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
  src/components/ModalFixRemindDate/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/constants/api.ts
  src/constants/createPlanSessionKey.ts
  src/hooks/apis/useEditRemindMutation.ts
  src/types/Remind.ts
  src/types/apis/plan/EditRemind.ts
  src/types/apis/plan/PostNewPlan.ts
  src/utils/getSessionData.ts
Labels: 🚨긴급

#297 [노철] - 타입 에러 수정
  src/components/KakaoShareButton/KakaoShareButton.tsx
Labels: 🚨긴급, 🐛버그

#300 [민우] - 작성 페이지 진입 로직 및 디자인 수정
  src/app/(header)/create/page.tsx
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/index.scss
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIcon/index.scss
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindDate/index.scss
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/DebounceSwitchButton/index.scss
  src/components/ModalContinueCreate/ModalContinueCreate.tsx
  src/components/ModalContinueCreate/index.scss
  src/constants/createPlanSessionKey.ts
  src/utils/getSessionData.ts
  src/utils/getSessionStorageData.ts
Labels: 💡중간

#305 [민우] - Error 컴포넌트 및 NotFound 컴포넌트 디자인
  src/app/not-found.scss
  src/app/not-found.tsx
  src/components/BasicError/BasicError.tsx
  src/components/BasicError/index.scss
Labels: 💡중간

#307 [혜수] - 랜딩페이지 아이콘 색상 변경
  src/app/_components/LandingPage/LandingPage.tsx
Labels: 🎶낮음

#308 [혜수] - 비회원일 때 계획 작성 토스트 오류 해결
  src/stores/canMakeNewPlanStore.ts
Labels: 💡중간

#309 [혜수] - 로딩 위치 변경
  src/app/(headerless)/loading.scss
  src/app/(headerless)/loading.tsx
  src/app/loading.scss
  src/app/loading.tsx
Labels: 🎶낮음

#310 [노철] - 페이지 디자인 수정
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/components/KakaoShareButton/KakaoShareButton.tsx
  src/components/KakaoShareButton/index.scss
  src/components/PlanInput/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/ToTopFloatingButton/ToTopFloatingButton.tsx
  src/components/ToTopFloatingButton/index.scss
Labels: 🚨긴급

#313 [혜수] - 작은 화면일 때 xl 폰트 사이즈 1.75rem으로 변경
  src/styles/class/font-size.scss
Labels: 🎶낮음

#314 [노철] - 로그인 페이지 마진 변경
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/login/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
Labels: 🚨긴급

#316 [노철] - 마이페이지 갭 변경
  src/app/(header)/my/index.scss
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/app/(headerless)/login/index.scss
Labels: 🚨긴급

#318 [노철] - 로그인페이지 이미지 변경
  public/loginPage/characters.svg
  public/loginPage/first.png
  public/loginPage/fourth.png
  public/loginPage/second.png
  public/loginPage/third.png
  src/app/(header)/my/page.tsx
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
Labels: 🚨긴급

#320 배포
  public/loginPage/characters.svg
  public/loginPage/first.png
  public/loginPage/fourth.png
  public/loginPage/second.png
  public/loginPage/third.png
  src/app/(header)/create/page.tsx
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/app/(headerless)/loading.scss
  src/app/(headerless)/loading.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/_components/LandingPage/LandingPage.tsx
  src/app/loading.scss
  src/app/loading.tsx
  src/app/not-found.scss
  src/app/not-found.tsx
  src/components/BasicError/BasicError.tsx
  src/components/BasicError/index.scss
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/index.scss
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIcon/index.scss
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindDate/index.scss
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/DebounceSwitchButton/index.scss
  src/components/KakaoShareButton/KakaoShareButton.tsx
  src/components/KakaoShareButton/index.scss
  src/components/ModalContinueCreate/ModalContinueCreate.tsx
  src/components/ModalContinueCreate/index.scss
  src/components/PlanInput/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/ToTopFloatingButton/ToTopFloatingButton.tsx
  src/components/ToTopFloatingButton/index.scss
  src/constants/createPlanSessionKey.ts
  src/stores/canMakeNewPlanStore.ts
  src/styles/class/font-size.scss
  src/utils/getSessionData.ts
  src/utils/getSessionStorageData.ts
Labels: 🍐배포

#321 [민우] - 리마인드 정보 조회, 수정 API 연결
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/reminds/[planId]/index.scss
  src/app/(header)/reminds/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIcon/index.scss
  src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/constants/editRemindStepTitle.ts
  src/types/Remind.ts
Labels: 💡중간

#325 [노철] - 쿠키 저장 및 라우팅 방식 변경
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
Labels: 🚨긴급

#327 [노철] - 쿠키 max-age 변경
  src/apis/axiosInstanceClient.ts
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/constants/cookie.ts
  src/stores/authStore.ts
Labels: 🚨긴급, 🐛버그

#331 [혜수] - 모달 기본 폰트 base로 변경
  src/components/Modal/ModalBasic.tsx
Labels: 🎶낮음

#332 [혜수] - 다른 계획 둘러보기 API 아이콘 적용
  src/app/(header)/explore/_components/Card/Card.tsx
  src/types/apis/plan/GetAllPlans.ts
Labels: 🚨긴급

#335 [혜수] - 네비게이션바에 계획 생성 가능 여부 전역상태관리 추가
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/constants/plan.ts
Labels: 🚨긴급

#338 [혜수] - Plan type API에 맞게 수정
  src/types/apis/plan/GetMyPlans.ts
Labels: 🚨긴급

#339 [민우] - 타인 리마인드 조회 불가능 처리 및 계획 작성 4개 이상 시 불가능 처리
  src/app/(header)/create/page.tsx
  src/app/(header)/reminds/[planId]/index.scss
  src/app/(header)/reminds/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/_hooks/useEditRemindPage.ts
  src/app/(header)/reminds/edit/[planId]/index.scss
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/constants/index.ts
  src/constants/userInputMaxLength.ts
  src/hooks/apis/useEditRemindMutation.ts
  src/hooks/useSessionStorage.ts
  src/middleware.ts
  src/types/Remind.ts
  src/utils/checkIsSeason.ts
Labels: 🚨긴급

#342 [노철]- 토큰 재발행 재귀 호출
  src/apis/axiosInstanceClient.ts
Labels: 🚨긴급

#343 [노철]- 계획api 업데이트
  src/apis/client/getPlan.ts
  src/app/(header)/my/_components/ModalRemindWay/ModalRemindWay.tsx
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/login/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/hooks/apis/useGetPlanQuery.ts
  src/hooks/useWritablePlan.ts
  src/types/Plan.ts
  src/types/apis/plan/EditPlan.ts
  src/types/apis/plan/GetPlan.ts
Labels: 🚨긴급

#340 [노철]- 도움말 버튼
  src/components/HelpButton/HelpButton.tsx
  src/components/HelpButton/index.scss
  src/types/IconName.ts
Labels: 🚨긴급

#350 [노철]- isMyPlan store
  src/app/(header)/plans/[planId]/page.tsx
  src/stores/isMyPlanStore.ts
Labels: 🚨긴급

#352 [혜수] - 위치에 따라 nav bar 표시 변경
  src/app/_components/Navigation/Navigation.tsx
Labels: 💡중간

#353 [혜수] - 계획 생성 시 최대 개수 일 때 작성하지 못하도록 수정
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/_components/Navigation/Navigation.tsx
Labels: 🚨긴급

#349 [민우] - 계획 작성, 리마인드 부분 나머지 작업
  src/app/(header)/create/index.scss
  src/components/CreatePlanIcon/index.scss
  src/components/CreatePlanRemindDate/index.scss
  src/components/CreatePlanRemindMessage/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/ReadOnlyRemind/index.scss
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/Remind/WritableRemind/index.scss
  src/components/WritablePlan/WritablePlan.tsx
  src/components/WritablePlan/index.scss
  src/components/index.ts
  src/styles/reset.scss
Labels: 🚨긴급

#355 [노철] - 도움말 버튼 적용
  public/notPublic.png
  src/app/(header)/plans/[planId]/_components/NotPublic/NotPublic.tsx
  src/app/(header)/plans/[planId]/_components/NotPublic/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/(headerless)/oauth/index.scss
  src/app/(headerless)/oauth/page.tsx
  src/components/HelpButton/index.scss
  src/components/InputTag/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/ReadOnlyPlan/index.scss
Labels: 🚨긴급

#357 [노철]- 타인 수정 페이지 접근 막기
  src/app/(header)/plans/edit/[planId]/page.tsx
Labels: 🚨긴급

#361 [혜수] - 계획 수정할 때 nav 홈으로 변경
  src/app/_components/Navigation/Navigation.tsx
Labels: 🚨긴급

#367 [혜수] - 둘러보기 페이지 UI 수정 & 홈 설문조사 링크 추가
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
Labels: 🚨긴급

#364 [민우] - 리마인드 수정 후 해당 리마인드 페이지로 돌아가도록
  src/app/(header)/reminds/edit/[planId]/page.tsx
Labels: 🚨긴급

#369 [민우] - 계획 작성 시 리마인드 알림 도움말 버튼 추가
  src/components/CreatePlanContent/CreatePlanContent.tsx
Labels: 🚨긴급

#368 [노철] - 수정페이지
  public/loginPage/characters.png
  public/loginPage/characters.svg
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/login/page.tsx
  src/components/KakaoShareButton/KakaoShareButton.tsx
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
Labels: 🚨긴급

#373 [노철] - 토글 에러 핸들링
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/hooks/apis/useToggleIsPublicMutation.ts
Labels: 🚨긴급

#371 [민우] - 배포 위한 변수 설정
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/postNewPlan.ts
Labels: 🚨긴급
