Repository New-Barams/this-year-ajaja-fe, pull requests merged in 2023-11, with the labels that each got.

#2 [민우] - 배포용 초기 페이지 설정
  src/app/page.tsx
Labels: 🍐배포

#4 [혜수] - Readme 수정
  README.md
Labels: 🎶낮음

#11 [혜수] - 메인 색상, 폰트 크기, border-radius, 그림자 추가
  next.config.js
  src/styles/origin-theme.scss
  src/styles/standard.scss
  src/styles/variables.scss
Labels: 🚨긴급

#19 [혜수] - dev branch에 merge시 연결된 issue 자동 close
  .github/workflows/close-issue.yml
Labels: 🎶낮음

#17 [혜수] - 공통 scss 배경색, 폰트색, 폰트 크기 추가
  .gitignore
  src/app/layout.tsx
  src/styles/class/background.scss
  src/styles/class/color.scss
  src/styles/class/font-size.scss
  src/styles/class/mixin.scss
  src/styles/origin-theme.scss
  src/styles/standard.scss
  src/styles/variables.scss
Labels: 🚨긴급

#21 [혜수] - border-radious -> border-radius로 수정
  src/styles/standard.scss
Labels: 🚨긴급

#14 [노철] - 태그 컴포넌트 구현
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/Tag/Tag.tsx
  src/components/Tag/index.scss
  src/components/index.ts
  src/types/Color.ts
Labels: 🎶낮음

#24 [혜수] - 아좌좌 button 공통 컴포넌트
  src/components/AjajaButton/AjajaButton.tsx
  src/components/AjajaButton/index.scss
  src/components/index.ts
Labels: 🚨긴급

#28 [혜수] - 공통 아좌좌 버튼 상태 컴포넌트 안으로 이동
  src/components/AjajaButton/AjajaButton.tsx
  src/hooks/useDebounce.ts
Labels: 🚨긴급

#29 [민우] - PlanInput, RemindInput 컴포넌트 구현
  src/components/PlanInput/PlanInput.tsx
  src/components/PlanInput/index.scss
  src/components/RemindInput/RemindInput.tsx
  src/components/RemindInput/index.scss
  src/styles/reset.scss
Labels: 💡중간

#32 [혜수] - 버튼 컴포넌트 리팩토링
  src/components/Button/Button.tsx
  src/components/Button/index.scss
  src/styles/class/border.scss
Labels: 💡중간

#33 [혜수] - 공통 modal 컴포넌트 완성
  src/components/Modal/Modal.tsx
  src/components/Modal/index.scss
  src/components/index.ts
Labels: 🚨긴급

#35 [민우] - Dropdown 컴포넌트 구현
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
  src/components/Icon/Icon.tsx
Labels: 🚨긴급

#37 [혜수] - 헤더 생성
  public/next.svg
  public/this-year-ajaja-logo.svg
  public/vercel.svg
  src/app/(header)/_components/Header/Header.tsx
  src/app/(header)/_components/Header/index.scss
  src/app/(header)/_components/LinkIconText/LinkIconText.tsx
  src/app/(header)/_components/LinkIconText/index.scss
  src/app/(header)/_components/index.scss
  src/app/(header)/layout.tsx
  src/components/Icon/Icon.tsx
  src/types/IconName.ts
  src/types/index.ts
Labels: 🚨긴급

#39 [민우] - CircleProgressBar 컴포넌트 구현
  package-lock.json
  package.json
  src/components/CircleProgressBar/CircleProgressBar.tsx
  src/components/CircleProgressBar/index.scss
  src/constants/color.ts
  src/constants/index.ts
Labels: 💡중간

#43 [전체] - 배포 1차 테스트
  .github/workflows/close-issue.yml
  .gitignore
  .prettierrc
  next.config.js
  package-lock.json
  package.json
  public/next.svg
  public/this-year-ajaja-logo.svg
  public/vercel.svg
  src/app/(header)/_components/Header/Header.tsx
  src/app/(header)/_components/Header/index.scss
  src/app/(header)/_components/LinkIconText/LinkIconText.tsx
  src/app/(header)/_components/LinkIconText/index.scss
  src/app/(header)/_components/index.scss
  src/app/(header)/layout.tsx
  src/app/layout.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/AjajaButton/index.scss
  src/components/Button/Button.tsx
  src/components/Button/index.scss
  src/components/CircleProgressBar/CircleProgressBar.tsx
  src/components/CircleProgressBar/index.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
  src/components/Icon/Icon.tsx
  src/components/Icon/index.scss
  src/components/IconSwitchButton/IconSwitchButton.tsx
  src/components/IconSwitchButton/index.scss
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/Modal/Modal.tsx
  src/components/Modal/index.scss
  src/components/PlanInput/PlanInput.tsx
  src/components/PlanInput/index.scss
  src/components/RemindInput/RemindInput.tsx
  src/components/RemindInput/index.scss
  src/components/SwitchButton/SwitchButton.tsx
  src/components/SwitchButton/index.scss
  src/components/Tag/Tag.tsx
  src/components/Tag/index.scss
  src/components/index.ts
  src/constants/color.ts
  src/constants/index.ts
  src/hooks/useDebounce.ts
  src/styles/class/background.scss
  src/styles/class/border.scss
  src/styles/class/color.scss
  src/styles/class/font-size.scss
  src/styles/class/mixin.scss
  src/styles/origin-theme.scss
  src/styles/reset.scss
  src/styles/standard.scss
  src/styles/variables.scss
  src/types/Color.ts
  src/types/FontSize.ts
  src/types/IconName.ts
  src/types/index.ts
  tsconfig.json
Labels: 🍐배포

#45 [노철] - use client 누락
  src/components/InputTag/InputTag.tsx
  src/components/Modal/Modal.tsx
Labels: 🚨긴급, 🐛버그

#49 [혜수] - 평가 모달 생성
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalEvaluate.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalRadio.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/index.scss
  src/components/Dropdown/index.scss
  src/components/Icon/Icon.tsx
  src/components/Modal/Modal.tsx
  src/components/Modal/ModalBasic.tsx
  src/components/Modal/index.scss
  src/components/PlanInput/index.scss
  src/components/index.ts
  src/hooks/useModalClose.ts
  src/styles/class/mixin.scss
  src/styles/standard.scss
  src/types/IconName.ts
Labels: 💡중간

#50 [노철] - 유저스토어 구현
  src/components/InputTag/InputTag.tsx
  src/hooks/useAuth.ts
  src/stores/authStore.ts
Labels: 🚨긴급

#51 [노철] - 로그인 페이지 구현
  public/kakao_login_large_narrow.png
  src/app/(header)/layout.tsx
  src/app/(headerless)/login/hooks/useLogin.ts
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauth.ts
  src/app/(headerless)/oauth/page.tsx
  src/app/layout.tsx
  src/constants/index.ts
  src/constants/login.ts
Labels: 💡중간

#54 [민우] - 작성 가능 리마인드 아이템 컴포넌트 구현
  src/components/Icon/Icon.tsx
  src/components/RemindInput/index.scss
  src/components/WritableRemindItem/WritableRemindItem.tsx
  src/components/WritableRemindItem/index.scss
  src/components/index.ts
  src/types/IconName.ts
Labels: 🚨긴급

#58 [혜수] - 인스턴스 생성
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/constants/api.ts
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/hooks/apis/users/useRefreshNameMutation.ts
  src/stores/authStore.ts
  src/types/axios/index.d.ts
Labels: 🚨긴급

#61 [혜수] - 내 계획 페이지 구현
  src/apis/axiosInstance.ts
  src/app/(header)/_components/index.scss
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
  src/app/(header)/home/_components/Plan/Plan.tsx
  src/app/(header)/home/_components/Plan/index.scss
  src/app/(header)/home/_components/ProgressBar/ProgressBar.tsx
  src/app/(header)/home/_components/ProgressBar/index.scss
  src/app/(header)/home/_components/index.scss
  src/app/(header)/home/page.tsx
  src/app/(headerless)/oauth/hooks/useOauth.ts
  src/app/layout.tsx
  src/components/Icon/Icon.tsx
  src/components/index.ts
  src/constants/planIcons.ts
  src/hooks/apis/plans/useMyPlansQuery.ts
  src/styles/webkit.scss
  src/types/IconName.ts
  src/types/apis/plan/GetMyPlans.ts
Labels: 💡중간

#65 [혜수] - API 인스턴스 서버, 클라이언트 분리
  src/apis/axiosInstanceClient.ts
  src/apis/axiosInstanceServer.ts
  src/apis/client/getAllPlans.ts
  src/apis/server/getMyPlans.ts
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/hooks/apis/plans/useMyPlansQuery.ts
Labels: 🚨긴급

#64 [민우] - 조회 가능 리마인드 아이템 컴포넌트 구현
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalEvaluate.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/components/CircleProgressBar/CircleProgressBar.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/ReadOnlyRemind/index.scss
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/Remind/WritableRemind/index.scss
  src/components/RemindInput/RemindInput.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/ReadOnlyRemindItem/index.scss
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/constants/components/remindOptions.ts
  src/types/components/Remind.ts
Labels: 🚨긴급

#67 [노철] - 계획 컴포넌트 구현
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/page.tsx
  src/components/IconSwitchButton/index.scss
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/ReadOnlyPlan/index.scss
  src/components/SwitchButton/index.scss
  src/components/Tag/index.scss
  src/components/index.ts
  src/hooks/apis/users/useRefreshNameMutation.ts
Labels: 🚨긴급

#72 [노철] - inputTag 에러
  src/components/InputTag/InputTag.tsx
Labels: 🐛버그

#74 [노철] - 수정, 쓰기를 위한 계획 컴포넌트
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/WritablePlan/WritablePlan.tsx
  src/components/WritablePlan/index.scss
Labels: 🚨긴급

#76 [민우] - 피드백 평가 모달, 디바운스 스위치 버튼 구현
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalEvaluate.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalRadio.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/components/DebounceSwitchButton/DebounceSwitchButton.tsx
  src/components/DebounceSwitchButton/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/types/components/Remind.ts
  src/utils/decideRandomIconNumber.ts
Labels: 💡중간

#78 [민우] - 작성 페이지, 수정 페이지 구현
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/Button/Button.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/WritablePlan/WritablePlan.tsx
Labels: 💡중간

#80 [노철] - 마이페이지
  src/app/(header)/my/_components/ModalVerification.tsx
  src/app/(header)/my/_components/index.scss
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
Labels: 💡중간

#82 [민우] - API 함수 및 리액트 쿼리 훅 구현
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/apis/client/postNewPlan.ts
  src/apis/client/toggleAjajaNotification.ts
  src/apis/client/toggleIsPublic.ts
  src/apis/client/toggleIsRemindable.ts
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
  src/components/Modal/ModalExit.tsx
  src/components/Modal/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/hooks/apis/usePostNewPlanMutation.ts
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/hooks/apis/useToggleIsPublicMutation.ts
  src/hooks/apis/useToggleIsRemindable.ts
  src/types/apis/plan/PostNewPlan.ts
Labels: 💡중간

#83 [혜수] 다른 계획 둘러보기 구현
  src/apis/client/getAllPlans.ts
  src/app/(header)/_components/index.scss
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/app/(header)/explore/_components/Plans/index.scss
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/explore/_components/Tab/index.scss
  src/app/(header)/explore/_components/index.scss
  src/app/(header)/explore/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/AjajaButton/index.scss
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/provider/TanstackQueryProvider.tsx
  src/types/apis/plan/GetAllPlans.ts
Labels: 💡중간

#85 [전체] 배포 3차
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/getAllPlans.ts
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/apis/client/postNewPlan.ts
  src/apis/client/toggleAjajaNotification.ts
  src/apis/client/toggleIsPublic.ts
  src/apis/client/toggleIsRemindable.ts
  src/app/(header)/_components/index.scss
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/app/(header)/explore/_components/Plans/index.scss
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/explore/_components/Tab/index.scss
  src/app/(header)/explore/_components/index.scss
  src/app/(header)/explore/page.tsx
  src/app/(header)/my/_components/ModalVerification.tsx
  src/app/(header)/my/_components/index.scss
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalEvaluate.tsx
  src/app/(header)/plans/[planId]/_components/ModalEvaluate/ModalRadio.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/AjajaButton/index.scss
  src/components/Button/Button.tsx
  src/components/DebounceSwitchButton/DebounceSwitchButton.tsx
  src/components/DebounceSwitchButton/index.scss
  src/components/Dropdown/Dropdown.tsx
  src/components/Dropdown/index.scss
  src/components/InputTag/InputTag.tsx
  src/components/InputTag/index.scss
  src/components/Modal/ModalExit.tsx
  src/components/Modal/index.scss
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/WritablePlan/WritablePlan.tsx
  src/components/WritablePlan/index.scss
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/hooks/apis/usePostNewPlanMutation.ts
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/hooks/apis/useToggleIsPublicMutation.ts
  src/hooks/apis/useToggleIsRemindable.ts
  src/provider/TanstackQueryProvider.tsx
  src/types/apis/plan/GetAllPlans.ts
  src/types/apis/plan/PostNewPlan.ts
  src/types/components/Remind.ts
  src/utils/decideRandomIconNumber.ts
Labels: 🍐배포

#91 [혜수] - 다른 계획 둘러보기 아좌좌 색 통일(자몽색)
  src/app/(header)/explore/_components/Card/Card.tsx
Labels: 🎶낮음

#90 [혜수] - 아좌좌 1000단위 K 제거
  src/components/AjajaButton/AjajaButton.tsx
Labels: 🎶낮음

#92 [혜수] - API 엔드 포인트 상수화 작업
  src/apis/axiosInstanceClient.ts
  src/apis/axiosInstanceServer.ts
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/getAllPlans.ts
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/apis/client/postNewPlan.ts
  src/apis/client/toggleAjajaNotification.ts
  src/apis/client/toggleIsPublic.ts
  src/apis/client/toggleIsRemindable.ts
  src/apis/server/getMyPlans.ts
  src/app/(headerless)/oauth/hooks/useOauth.ts
  src/constants/api.ts
Labels: 💡중간

#96 [혜수] - Github Actions dev -> main 머지 자동화
  .github/actions/slack-notify.yml
  .github/workflows/merge-to-main.yml
Labels: 🎶낮음

#93 [노철] - to top floating button 구현
  src/app/(header)/_components/index.scss
  src/app/(header)/layout.tsx
  src/components/Icon/Icon.tsx
  src/components/ToTopFloatingButton/ToTopFloatingButton.tsx
  src/components/ToTopFloatingButton/index.scss
  src/components/index.ts
  src/hooks/useThrottle.ts
  src/types/IconName.ts
Labels: 💡중간

#98 [노철] - useAuth 변경
  src/apis/client/getTokenWithCode.ts
  src/app/(headerless)/login/hooks/useLogin.ts
  src/app/(headerless)/login/hooks/useLoginPage.ts
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauth.ts
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/(headerless)/oauth/page.tsx
  src/constants/login.ts
  src/hooks/useAuth.ts
  src/hooks/useIsLogIn.ts
  src/types/apis/login/getTokenWithCoin.ts
Labels: 🚨긴급

#102 [전체] - 배포
  src/apis/axiosInstanceClient.ts
  src/apis/axiosInstanceServer.ts
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/getAllPlans.ts
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/apis/client/getTokenWithCode.ts
  src/apis/client/postNewPlan.ts
  src/apis/client/toggleAjajaNotification.ts
  src/apis/client/toggleIsPublic.ts
  src/apis/client/toggleIsRemindable.ts
  src/apis/server/getMyPlans.ts
  src/app/(header)/_components/index.scss
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/layout.tsx
  src/app/(headerless)/login/hooks/useLogin.ts
  src/app/(headerless)/login/hooks/useLoginPage.ts
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauth.ts
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/(headerless)/oauth/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/Icon/Icon.tsx
  src/components/ToTopFloatingButton/ToTopFloatingButton.tsx
  src/components/ToTopFloatingButton/index.scss
  src/components/index.ts
  src/constants/api.ts
  src/constants/login.ts
  src/hooks/useAuth.ts
  src/hooks/useIsLogIn.ts
  src/hooks/useThrottle.ts
  src/types/IconName.ts
  src/types/apis/login/getTokenWithCoin.ts
Labels: 🍐배포

#106 [전체]- 배포
  src/app/layout.tsx
Labels: 🍐배포

#108 [전체] - meta tag 삭제
  src/app/layout.tsx
Labels: 🐛버그

#110 [전체] - 배포
  src/app/layout.tsx
Labels: 🍐배포

#112 [혜수] - Mixed Content 문제 rewrite 이용
  next.config.js
Labels: 🐛버그

#113 [전체] - 배포
  next.config.js
Labels: 🍐배포

#114 💩 : #111 rewrite 제거
  next.config.js
Labels: 🐛버그

#100 [노철] - 상세페이지 토글 버튼 수정
  src/components/DebounceSwitchButton/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/index.ts
Labels: 🚨긴급

#116 [혜수] - 내 계획 페이지 추가 수정
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/page.tsx
  src/utils/checkThisYear.ts
Labels: 💡중간

#118 [노철]- 로그인 api 함수 상수화
  src/apis/client/getTokenWithCode.ts
  src/constants/api.ts
Labels: 🚨긴급

#120 [민우] - 실제 API 연결 및 오류 해결
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/getRemindAfterSeason.ts
  src/apis/client/getRemindSeason.ts
  src/apis/client/postNewPlan.ts
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/constants/api.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/types/apis/plan/EditPlan.ts
  src/types/apis/plan/PostNewPlan.ts
  src/types/apis/remind/getRemind.ts
  src/types/components/Remind.ts
  src/utils/changeRemindTimeToNumber.ts
  src/utils/changeRemindTimeToString.ts
  src/utils/checkIsSeason.ts
  src/utils/getUserIdFromJWT.ts
Labels: 🚨긴급

#121 [혜수] - API 연결 작업 준비 - Hook 만들어 놓기
  src/apis/client/getAllPlans.ts
  src/apis/client/getAllPlansMock.ts
  src/apis/client/postAaja.ts
  src/apis/server/getMyPlans.ts
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
  src/app/(header)/home/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/constants/api.ts
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/types/apis/plan/GetAllPlans.ts
  src/types/apis/plan/GetMyPlans.ts
Labels: 💡중간

#125 [혜수] - 내 계획 페이지 계획 클릭시 올바른 planId 경로로 들어가도록 추가
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/Plan/Plan.tsx
Labels: 🚨긴급

#126 [혜수] - 피드백 API 생성
  src/apis/client/postFeedback.ts
  src/constants/api.ts
  src/hooks/apis/feedback/usePostFeedbackMutation.ts
  src/types/apis/feedback/PostFeedbaks.ts
Labels: 🚨긴급

#128 [혜수] - 내 계획 페이지 API server -> client로 변경
  src/apis/client/getMyPlans.ts
  src/app/(header)/home/page.tsx
  src/hooks/apis/plans/useGetMyPlansQuery.ts
Labels: 💡중간

#130 [혜수] - 로그인 여부에 따라 헤더 텍스트 변경
  src/app/(header)/_components/Header/Header.tsx
  src/app/(header)/_components/LinkIconText/LinkIconText.tsx
Labels: 🚨긴급

#134 [노철] - 로그인 방식 변경
  src/apis/client/getTokenWithCode.ts
  src/constants/api.ts
  src/types/apis/login/getTokenWithCoin.ts
Labels: 🚨긴급

#131 [노철] - api 함수 정의 및 페이지 적용
  src/apis/client/getPlan.ts
  src/apis/client/getTokenWithCode.ts
  src/apis/client/getUserInformation.ts
  src/apis/client/postUsersLogOut.ts
  src/apis/client/refreshNickname.ts
  src/apis/client/requestEmailVerification.ts
  src/apis/client/submitEmailVerificationCode.ts
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/login/hooks/useLoginPage.ts
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/index.ts
  src/constants/api.ts
  src/hooks/apis/useGetPlanQuery.ts
  src/hooks/apis/useGetUserInformationQuery.ts
  src/hooks/apis/useRefreshNicknameMutation.ts
  src/types/apis/plan/GetPlan.ts
  src/types/apis/users/GetTokenWithCoin.ts
  src/types/apis/users/GetUserInformation.ts
  src/types/apis/users/RefreshNickname.ts
  src/types/apis/users/RequestEmailVerification.ts
Labels: 🚨긴급

#136 [민우] - 상세 페이지 초기 진입 로직 추가 및 임시 로딩 페이지 구현
  package-lock.json
  package.json
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/loading.scss
  src/app/loading.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/constants/api.ts
  src/hooks/apis/useGetPlanQuery.ts
  src/utils/checkIsMyPlan.ts
  src/utils/checkIsSeason.ts
Labels: 💡중간

#139 [혜수] - 내 계획 페이지 이메일 인증 여부 추가
  src/app/(header)/_components/index.scss
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/index.scss
Labels: 💡중간

#138 [노철] - 마이페이지
  src/apis/client/deleteUsers.ts
  src/apis/client/postLogin.ts
  src/apis/client/postSendVerification.ts
  src/apis/client/postUsersRefresh.ts
  src/apis/client/postVerify.ts
  src/apis/client/refreshNickname.ts
  src/apis/client/requestEmailVerification.ts
  src/apis/client/submitEmailVerificationCode.ts
  src/app/(header)/my/page.tsx
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/components/ModalVerification/ModalVerification.tsx
  src/constants/api.ts
  src/hooks/apis/usePostSendVerificationMutation.ts
  src/hooks/apis/usePostVerifyMutation.ts
  src/hooks/apis/useRefreshNicknameMutation.ts
  src/types/apis/users/GetTokenWithCoin.ts
  src/types/apis/users/PostSendVerification.ts
  src/types/apis/users/PostUsersRefresh.ts
  src/types/apis/users/RefreshNickname.ts
  src/types/apis/users/RequestEmailVerification.ts
  src/utils/checkEmailValidation.ts
Labels: 🚨긴급

#141 [혜수] - 스타일 변경
  public/this-year-ajaja-logo-old.svg
  public/this-year-ajaja-logo.svg
  src/app/(header)/_components/Header/Header.tsx
  src/app/(header)/_components/LinkIconText/index.scss
  src/app/layout.tsx
Labels: 🎶낮음

#147 [혜수] - 로딩 하위 페이지에서 되도록 변경
  src/app/(header)/loading.scss
  src/app/(header)/loading.tsx
  src/app/(headerless)/loading.scss
  src/app/(headerless)/loading.tsx
Labels: 🎶낮음

#148 [혜수] - Ajaja 버튼에 planId 넣도록 수정
  src/components/AjajaButton/AjajaButton.tsx
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/hooks/apis/usePostAjajaMutation.ts
Labels: 🐛버그

#151 [민우] - 각 페이지 진입 및 완료 로직
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/components/Dropdown/Dropdown.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/useGetPlanQuery.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/hooks/apis/usePostNewPlanMutation.ts
  src/hooks/apis/useToggleIsRemindable.ts
  src/middleware.ts
Labels: 🚨긴급

#152 [노철] - 로그아웃, 회원탈퇴 리팩토링
  src/apis/client/postVerify.ts
  src/app/(header)/my/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/components/ModalVerification/ModalVerification.tsx
  src/constants/login.ts
Labels: 🚨긴급

#156 [혜수] - getAllPlans 토큰이 필요하지 않도록 수정
  src/apis/client/getAllPlans.ts
  src/app/(headerless)/login/page.tsx
Labels: 🚨긴급, 🐛버그

#160 [노철] - 실제 로그인 연결
  src/apis/client/postLogin.ts
  src/constants/api.ts
  src/types/apis/users/GetTokenWithCoin.ts
Labels: 🚨긴급

#163 [혜수] - 계획이 비어있을 때 email_isVerified 체크 오류 해결
  src/app/(header)/home/_components/MyPlan.tsx
Labels: 🚨긴급, 🐛버그

#157 [혜수] - 이메일 인증여부에 따라 새 계획 생성시 이메일 인증 모달 띄우기 추가
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
Labels: 💡중간

#168 [혜수] - 무한 스크롤 구현
  package-lock.json
  package.json
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/explore/_components/index.scss
  src/components/AjajaButton/AjajaButton.tsx
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/types/apis/plan/GetAllPlans.ts
Labels: 💡중간

#167 [민우] - mutation 무효화 로직 추가
  src/app/(header)/edit/[planId]/page.tsx
  src/components/Dropdown/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/hooks/apis/feedback/usePostFeedbackMutation.ts
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/useGetRemindQuery.ts
  src/hooks/apis/usePostNewPlanMutation.ts
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/hooks/apis/useToggleIsPublicMutation.ts
  src/hooks/apis/useToggleIsRemindable.ts
Labels: 💡중간

#171 [혜수] - 쿼리키 상수로 변경
  src/app/(header)/home/_components/MyPlan.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/hooks/apis/plans/useAllPlansQuery.ts
  src/hooks/apis/plans/useGetMyPlansQuery.ts
  src/hooks/apis/useGetUserInformationQuery.ts
Labels: 🎶낮음

#166 [노철] - api 에러 핸들링
  src/apis/client/postSendVerification.ts
  src/apis/client/postVerify.ts
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/components/ModalVerification/ModalVerification.tsx
  src/hooks/apis/useGetPlanQuery.ts
  src/hooks/apis/useGetUserInformationQuery.ts
  src/hooks/apis/usePostSendVerificationMutation.ts
  src/hooks/apis/usePostVerifyMutation.ts
  src/utils/checkEmailValidation.ts
Labels: 💡중간

#174 [혜수] - 로그인 하지 않은 유저일 때 카드 컴포넌트 클릭 시 로그인 유도 모달 추가
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/components/Modal/index.scss
Labels: 🚨긴급, 🐛버그

#175 [혜수] - 다른 계획 둘러보기 페이지에서 아좌좌 수 정상적으로 보이도록 변경
  src/app/(header)/explore/_components/Plans/Plans.tsx
  src/components/AjajaButton/AjajaButton.tsx
Labels: 💡중간

#180 [혜수] - handleSetVerifiedEmail Promise.all로 변경
  src/app/(header)/home/_components/MyPlan.tsx
Labels: 🎶낮음

#178 [노철] - 마이페이지 스타일 수정
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
Labels: 💡중간

#188 [혜수] - React Query Error handling
  src/apis/client/postAjaja.ts
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/error.tsx
  src/app/(header)/home/error.tsx
  src/app/(header)/home/page.tsx
  src/components/AjajaButton/AjajaButton.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/hooks/apis/useAllPlansQuery.ts
  src/hooks/apis/useGetMyPlansQuery.ts
  src/hooks/apis/usePostAjajaMutation.ts
  src/hooks/apis/usePostFeedbackMutation.ts
Labels: 🚨긴급

#196 [혜수] - 계획 주기 확정 버튼 sm 크기 키우기
  src/components/Button/index.scss
Labels: 🎶낮음

#197 [노철] - react query 에러핸들링
  src/app/(header)/my/error.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/hooks/apis/useGetPlanQuery.ts
  src/hooks/apis/useGetUserInformationQuery.ts
  src/hooks/apis/useRefreshNicknameMutation.ts
Labels: 🚨긴급

#199 [민우] - icon 오류 해결 및 리마인드 옵션 확정 버튼 로직 수정
  src/app/layout.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
Labels: 🚨긴급

#201 [노철] - 이메일 인증 모달 style 수정
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
Labels: 💡중간

#205 [노철] - 회원탈퇴 api
  src/app/(header)/my/page.tsx
  src/constants/api.ts
  src/types/apis/users/GetUserInformation.ts
Labels: 🚨긴급

#206 [혜수] - 페이지 맨 밑 잘 안보이는 현상 해결
  src/app/(header)/_components/Header/index.scss
  src/app/(header)/_components/LinkIconText/index.scss
  src/app/(header)/_components/index.scss
  src/app/(header)/layout.tsx
  src/styles/reset.scss
Labels: 🎶낮음

#212 [혜수] - next.js 디버깅 파일 추가
  .vscode/launch.json
  src/app/(header)/home/_components/MyPlan.tsx
Labels: 🎶낮음

#210 [혜수] - 이메일 인증여부 마이페이지 API 연결 (임시)
  src/app/(header)/home/_components/MyPlan.tsx
Labels: 🐛버그

#214 [노철] - 스타일 수정
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/components/InputTag/index.scss
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/Tag/index.scss
  src/components/WritablePlan/WritablePlan.tsx
Labels: 🚨긴급, 🐛버그

#215 [혜수] - toast 추가
  package-lock.json
  package.json
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/components/Svg/ErrorToast.tsx
  src/components/Svg/SuccessToast.tsx
  src/components/Toaster/Toaster.tsx
  src/components/Toaster/customToast.tsx
  src/components/Toaster/index.scss
  src/components/index.ts
  src/provider/Provider.tsx
  src/types/Svg.ts
Labels: 💡중간

#217 [노철] - 로그인 관련 토스트 적용
  src/app/(header)/my/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
Labels: 🚨긴급

#219 [민우] - 작성, 수정, 상세 페이지 디자인 수정 및 에러 해결 및 토스트 적용
  src/app/(header)/create/index.scss
  src/app/(header)/create/page.tsx
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/edit/[planId]/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/components/Dropdown/index.scss
  src/components/PlanInput/PlanInput.tsx
  src/components/PlanInput/index.scss
  src/components/Remind/ReadOnlyRemind/index.scss
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/Remind/WritableRemind/index.scss
  src/components/RemindInput/RemindInput.tsx
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/components/RemindItem/WritableRemindItem/index.scss
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/usePostNewPlanMutation.ts
Labels: 🚨긴급

#223 [민우] - 특정 api 호출 실패 시 error 토스트 연결
  src/hooks/apis/useDeletePlanMutation.ts
  src/hooks/apis/useEditPlanMutation.ts
  src/hooks/apis/usePostFeedbackMutation.ts
  src/hooks/apis/usePostNewPlanMutation.ts
Labels: 💡중간

#226 [민우] - 디자인 수정
  src/app/(header)/create/index.scss
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/plans/[planId]/index.scss
  src/components/Dropdown/index.scss
  src/components/PlanInput/PlanInput.tsx
  src/components/Remind/ReadOnlyRemind/ReadOnlyRemind.tsx
  src/components/Remind/WritableRemind/WritableRemind.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/ReadOnlyRemindItem/index.scss
  src/components/RemindItem/WritableRemindItem/index.scss
  src/components/WritablePlan/WritablePlan.tsx
Labels: 🚨긴급

#227 [혜수] - 내 계획 페이지 스타일 수정
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
  src/app/(header)/home/_components/Plan/Plan.tsx
  src/app/(header)/home/_components/Plan/index.scss
  src/app/(header)/home/_components/index.scss
  src/components/Tag/Tag.tsx
Labels: 🎶낮음

#230 [혜수] - 스크롤바 윈도우 크롬에서도 바뀐 스타일 볼 수 있도록 변경
  src/app/(header)/_components/Content.tsx
  src/app/(header)/create/index.scss
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/explore/_components/index.scss
  src/app/(header)/layout.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/styles/webkit.scss
  src/utils/checkIsSeason.ts
Labels: 🎶낮음

#235 [노철] - 마이페이지 디자인 수정
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
Labels: 🚨긴급, 🐛버그

#237 [전체]- 배포
  src/app/(header)/_components/Content.tsx
  src/app/(header)/create/index.scss
  src/app/(header)/edit/[planId]/index.scss
  src/app/(header)/explore/_components/index.scss
  src/app/(header)/layout.tsx
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/styles/webkit.scss
  src/utils/checkIsSeason.ts
Labels: 🍐배포

#239 [혜수] - 무한스크롤 되지 않는 오류 해결
  src/app/(header)/_components/Content.tsx
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/index.scss
  src/hooks/useScroll.ts
Labels: 🐛버그
