Repository New-Barams/this-year-ajaja-fe, pull requests merged in 2024-02, with the labels that each got.

#451 [노철] - 타입, 파일 정리
  package-lock.json
  package.json
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/IntroduceSwiper.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/components/index.ts
Labels: 🚨긴급

#453 [혜수] - 사용하지 않는 파일 삭제 & types 정리
  src/app/(header)/_components/Content.tsx
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(headerless)/notice/page.tsx
  src/app/feedback/[planId]/page.tsx
  src/app/feedback/evaluate/page.tsx
  src/hooks/useScroll.ts
  src/types/apis/feedback/PostFeedbacks.ts
  src/types/apis/index.ts
  src/types/apis/plan/GetPlan.ts
  src/types/index.ts
Labels: 🎶낮음

#455 [전체] - 배포
  package-lock.json
  package.json
  src/app/(header)/_components/Content.tsx
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/reminds/[planId]/page.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/IntroduceSwiper.tsx
  src/app/(headerless)/login/_components/IntroduceSwiper/index.scss
  src/app/(headerless)/notice/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/app/feedback/[planId]/page.tsx
  src/app/feedback/evaluate/page.tsx
  src/components/CircleProgressBar/CircleProgressBar.tsx
  src/components/CircleProgressBar/index.scss
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/index.ts
  src/constants/index.ts
  src/hooks/useScroll.ts
  src/types/apis/feedback/PostFeedbacks.ts
  src/types/apis/index.ts
  src/types/apis/plan/GetPlan.ts
  src/types/index.ts
Labels: 🍐배포

#457 ♻️ : #452 - postfeedbaks 오타 수정
  src/apis/client/postFeedbacks.ts
Labels: 🐛버그

#459 [전체] - 배포
  src/apis/client/postFeedbacks.ts
Labels: 🍐배포

#462 [혜수] - 피드백 퍼센트 관련 잘못된 조건 수정 완료
  src/components/FeedbackItem/FeedbackItem.tsx
Labels: 🚨긴급

#465 [전체] - 배포
  src/app/feedback/evaluate/_components/index.scss
  src/components/FeedbackItem/FeedbackItem.tsx
Labels: 🍐배포

#466 [민우] - 각 파일 import문 수정
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/app/(header)/create/page.tsx
  src/app/(header)/reminds/edit/[planId]/_hooks/useEditRemindPage.ts
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/ModalContinueCreate/ModalContinueCreate.tsx
  src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
  src/components/ModalSelectIcon/ModalSelectIcon.tsx
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/RemindItem/ReadOnlyRemindItem/ReadOnlyRemindItem.tsx
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/hooks/apis/index.ts
  src/hooks/index.ts
  src/utils/decideRandomIconNumber.ts
  src/utils/index.ts
Labels: 💡중간

#470 [혜수] - 비즈니스 로직 분리
  src/app/(header)/_components/Content.tsx
  src/app/(header)/_components/Header/Header.tsx
  src/app/(header)/_components/Header/index.scss
  src/app/(header)/_components/LinkIconText/LinkIconText.tsx
  src/app/(header)/_components/LinkIconText/index.scss
  src/app/(header)/_components/index.scss
  src/app/(header)/explore/_components/ExplorePlans.tsx
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/explore/_components/hooks/index.ts
  src/app/(header)/explore/_components/hooks/useExplorePlans.ts
  src/app/(header)/explore/_components/hooks/useTab.ts
  src/app/(header)/home/_components/MyPlan.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/ProgressBar/ProgressBar.tsx
  src/app/(header)/home/_components/hooks/index.ts
  src/app/(header)/home/_components/hooks/useHomePage.ts
  src/app/(header)/home/_components/hooks/useMyPlan.ts
  src/app/(header)/home/_components/hooks/useNewPlan.ts
  src/app/(header)/home/_components/hooks/useProgressBar.ts
  src/app/(header)/home/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/app/_components/hooks/index.ts
  src/app/_components/hooks/useNavigation.ts
  src/app/feedback/[planId]/_components/hooks/index.ts
  src/app/feedback/[planId]/_components/hooks/usePlanIdPage.ts
  src/app/feedback/[planId]/page.tsx
  src/app/feedback/evaluate/_components/EvaluateRadio.tsx
  src/app/feedback/evaluate/_components/hooks/index.ts
  src/app/feedback/evaluate/_components/hooks/useEvaluatePage.ts
  src/app/feedback/evaluate/_components/hooks/useEvaluateRadio.ts
  src/app/feedback/evaluate/page.tsx
  src/constants/addressRegex.ts
  src/constants/index.ts
  src/constants/radio.ts
  src/types/ProgressBar.ts
  src/types/Radio.ts
  src/types/Tab.ts
  src/types/index.ts
Labels: 💡중간

#471 [노철] - 비지니스 로직 분리
  src/app/(header)/my/hooks/useMyPage.tsx
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/hooks/usePlanPage.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/hooks/usePlanEditPage.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/login/hooks/useLoginPage.ts
Labels: 🚨긴급

#473 [혜수] - PR시 build 작업 추가 (CI)
  .github/workflows/nodejs.yml
Labels: 🎶낮음

#476 [혜수] - 브랜치명 develop -> dev로 변경
  .github/workflows/nodejs.yml
Labels: 🎶낮음

#479 [혜수] - 포크 자동화 ACTION 추가
  .github/workflows/sync-fork.yml
Labels: 🎶낮음

#482 [민우] - 비즈니스 로직 분리
  src/app/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/app/create/hooks/useCreatePage.ts
  src/app/create/page.tsx
  src/app/reminds/[planId]/hooks/useRemindPage.ts
  src/app/reminds/[planId]/page.tsx
  src/app/reminds/edit/[planId]/_hooks/useEditRemindPage.ts
  src/app/reminds/edit/[planId]/hooks/useEditRemindPage.ts
  src/app/reminds/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/hooks/useCreatePlanContent.ts
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIcon/hooks/useCreatePlanIcon.ts
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindDate/hooks/useCreatePlanRemindDate.ts
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/hooks/useCreatePlanRemindMessage.ts
  src/utils/index.ts
Labels: 💡중간
