Repository New-Barams/this-year-ajaja-fe, pull requests merged in 2024-01, with the labels that each got.

#376 [노철] - 쿠키 저장 시간 변경
  src/constants/cookie.ts
Labels: 🚨긴급

#374 [전체] - 배포
  public/loginPage/characters.png
  public/loginPage/characters.svg
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/postNewPlan.ts
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/explore/_components/Tab/Tab.tsx
  src/app/(header)/home/_components/NewPlan/NewPlan.tsx
  src/app/(header)/home/_components/NewPlan/index.scss
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(header)/reminds/edit/[planId]/page.tsx
  src/app/(headerless)/login/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/KakaoShareButton/KakaoShareButton.tsx
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/constants/cookie.ts
  src/hooks/apis/useToggleAjajaNotificationMutation.ts
  src/hooks/apis/useToggleIsPublicMutation.ts
Labels: 🚨긴급

#378 [민우] - 계획 작성, 삭제, 수정 시 header 값 오류
  src/apis/client/deletePlan.ts
  src/apis/client/editPlan.ts
  src/apis/client/postNewPlan.ts
Labels: 💡중간

#381 [민우] - 계획 작성 API 호출 시 생략된 field 추가
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/types/apis/plan/PostNewPlan.ts
Labels: 🚨긴급

#382 [hotfix] - 계획 작성 API 호출 시 생략된 field 추가
  src/app/(header)/create/_components/StepButtonGroup/StepButtonGroup.tsx
  src/types/apis/plan/PostNewPlan.ts
Labels: 🚨긴급

#384 [hotfix] - 로그인 페이지 오타 수정
  src/app/(headerless)/login/page.tsx
Labels: 🚨긴급, 🐛버그

#387 [노철] - 토큰 재발행 에러
  src/apis/axiosInstanceClient.ts
  src/utils/checkIsTokenExpired.ts
  src/utils/checkTokenExp.ts
Labels: 🚨긴급

#389 [전체]-배포
  src/apis/axiosInstanceClient.ts
  src/utils/checkIsTokenExpired.ts
  src/utils/checkTokenExp.ts
Labels: 🍐배포

#392 [민우] - 계획 작성 시 아이콘 선택 로직 수정
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
Labels: 🚨긴급

#396 [민우] - 리마인드 날짜 확정 모달 디자인 변경
  src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
  src/components/ModalFixRemindDate/index.scss
Labels: 💡중간

#393 [노철]- 수정, 마이페이지
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/components/PlanInput/PlanInput.tsx
Labels: 🚨긴급

#399 [노철] - 비공개 계획
  public/notPublic.png
  public/threeAnimals.png
  src/apis/axiosInstanceClient.ts
  src/app/(header)/plans/[planId]/_components/NotPublic/NotPublic.tsx
  src/app/(header)/plans/[planId]/_components/SearchingPlan/SearchingPlan.tsx
  src/app/(header)/plans/[planId]/_components/SearchingPlan/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/layout.tsx
  src/utils/alertAndLogin.ts
Labels: 🚨긴급

#401 [전체] - 배포
  public/notPublic.png
  public/threeAnimals.png
  src/apis/axiosInstanceClient.ts
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/_components/NotPublic/NotPublic.tsx
  src/app/(header)/plans/[planId]/_components/SearchingPlan/SearchingPlan.tsx
  src/app/(header)/plans/[planId]/_components/SearchingPlan/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/layout.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanIconExample/CreatePlanIconExample.tsx
  src/components/ModalFixRemindDate/ModalFixRemindDate.tsx
  src/components/ModalFixRemindDate/index.scss
  src/components/ModalVerification/ModalVerification.tsx
  src/components/ModalVerification/index.scss
  src/components/PlanInput/PlanInput.tsx
  src/utils/alertAndLogin.ts
Labels: 🍐배포

#403 [노철]- 이메일 인증 에러 핸들링
  src/app/layout.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/hooks/apis/usePostSendVerificationMutation.ts
  src/hooks/apis/usePostVerifyMutation.ts
Labels: 🚨긴급

#405 [혜수] 피드백 페이지 생성
  src/apis/client/getFeedbacks.ts
  src/apis/client/postFeedback.ts
  src/apis/client/postFeedbacks.ts
  src/app/(header)/home/_components/Plan/Plan.tsx
  src/app/feedback/[planId]/_components/index.scss
  src/app/feedback/[planId]/page.tsx
  src/app/feedback/evaluate/_components/EvaluateRadio.tsx
  src/app/feedback/evaluate/_components/index.scss
  src/app/feedback/evaluate/page.tsx
  src/components/FeedbackItem/FeedbackItem.tsx
  src/components/FeedbackItem/index.scss
  src/components/Icon/Icon.tsx
  src/components/WrongApproach/WrongApproach.tsx
  src/components/WrongApproach/index.scss
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/apis/useGetFeedbacksQuery.ts
  src/hooks/apis/usePostFeedbacksMutation.ts
  src/styles/class/font-size.scss
  src/types/Feedbacks.ts
  src/types/IconName.ts
  src/types/apis/feedback/GetFeedbacks.ts
  src/types/apis/feedback/PostFeedbaks.ts
Labels: 💡중간

#406 [노철] - 로그인 후 이전페이지 이동
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/layout.tsx
  src/components/RouteChangeObserver/RouteChangeObserver.tsx
Labels: 💡중간

#411 [노철] - 계획 상세 피드백 버튼 활성화
  src/app/(header)/plans/[planId]/page.tsx
Labels: 🚨긴급

#412 [노철] - 마이페이지 리팩토링
  src/app/(header)/my/page.tsx
  src/components/ModalVerification/ModalVerification.tsx
Labels: 🚨긴급

#409 [전체] - 배포
  src/apis/client/getFeedbacks.ts
  src/apis/client/postFeedback.ts
  src/apis/client/postFeedbacks.ts
  src/app/(header)/home/_components/Plan/Plan.tsx
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(headerless)/oauth/hooks/useOauthPage.ts
  src/app/feedback/[planId]/_components/index.scss
  src/app/feedback/[planId]/page.tsx
  src/app/feedback/evaluate/_components/EvaluateRadio.tsx
  src/app/feedback/evaluate/_components/index.scss
  src/app/feedback/evaluate/page.tsx
  src/app/layout.tsx
  src/components/FeedbackItem/FeedbackItem.tsx
  src/components/FeedbackItem/index.scss
  src/components/Icon/Icon.tsx
  src/components/ModalVerification/ModalVerification.tsx
  src/components/RouteChangeObserver/RouteChangeObserver.tsx
  src/components/WrongApproach/WrongApproach.tsx
  src/components/WrongApproach/index.scss
  src/constants/api.ts
  src/constants/queryKey.ts
  src/hooks/apis/useGetFeedbacksQuery.ts
  src/hooks/apis/usePostFeedbacksMutation.ts
  src/hooks/apis/usePostSendVerificationMutation.ts
  src/hooks/apis/usePostVerifyMutation.ts
  src/styles/class/font-size.scss
  src/types/Feedbacks.ts
  src/types/IconName.ts
  src/types/apis/feedback/GetFeedbacks.ts
  src/types/apis/feedback/PostFeedbaks.ts
Labels: 🍐배포

#415 [민우] - 리마인드 메세지 예시로 보내보기 기능 모달 UI 작업
  public/remind_example_email_temp.png
  public/remind_example_kakao.png
  src/app/(headerless)/login/index.scss
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/ModalSendRemindExample/ModalSendRemindExample.tsx
  src/components/ModalSendRemindExample/index.scss
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
Labels: 💡중간

#414 [노철] - 태그 컴포넌트 수정
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/index.scss
  src/components/DeletableTag/DeletableTag.tsx
  src/components/DeletableTag/index.scss
  src/components/Icon/Icon.tsx
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/index.scss
  src/components/index.ts
  src/hooks/useWritablePlan.ts
  src/types/IconName.ts
Labels: 🚨긴급, 🐛버그

#422 [민우] - 공지사항 페이지 구현
  src/app/(headerless)/notice/error.tsx
  src/app/(headerless)/notice/index.scss
  src/app/(headerless)/notice/page.tsx
Labels: 💡중간

#427 [민우] - 리마인드 예시 보내보기 API 연동 작업
  src/apis/client/postRemindTest.ts
  src/components/ModalSendRemindExample/ModalSendRemindExample.tsx
  src/constants/api.ts
  src/hooks/apis/usePostRemindTest.ts
Labels: 🚨긴급

#429 [민우] - 공지사항 페이지 내용 추가
  src/app/(headerless)/notice/index.scss
  src/app/(headerless)/notice/page.tsx
Labels: 🚨긴급

#425 [혜수] - 둘러보기 카드에서 올해 작성한 계획은 년도 제거하고 날짜 넣기
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
Labels: 🚨긴급

#426 [혜수] - 스크롤바가 항상 보이도록 변경
  src/styles/webkit.scss
Labels: 🚨긴급

#424 [혜수] - 네비게이션바 아이콘 색상이 바뀔 때 글자 색상은 변경되지 않는 문제 해결
  src/app/_components/Navigation/Navigation.tsx
Labels: 🚨긴급

#418 [노철] - 카카오 로그인 버튼 수정
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
Labels: 🚨긴급

#431 [노철] - 마이페이지 공지사항 추가
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
Labels: 🚨긴급

#433 [민우] - 리마인드 미리 보내보기 이메일 예시 이미지 변경
  public/remind_example_email.png
  src/components/ModalSendRemindExample/ModalSendRemindExample.tsx
Labels: 🚨긴급

#435 [전체] - 배포
  public/remind_example_email.png
  public/remind_example_email_temp.png
  public/remind_example_kakao.png
  src/apis/client/postRemindTest.ts
  src/app/(header)/explore/_components/Card/Card.tsx
  src/app/(header)/explore/_components/Card/index.scss
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/(headerless)/login/index.scss
  src/app/(headerless)/login/page.tsx
  src/app/(headerless)/notice/error.tsx
  src/app/(headerless)/notice/index.scss
  src/app/(headerless)/notice/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanContent/index.scss
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/components/CreatePlanRemindMessage/index.scss
  src/components/DeletableTag/DeletableTag.tsx
  src/components/DeletableTag/index.scss
  src/components/Icon/Icon.tsx
  src/components/ModalSendRemindExample/ModalSendRemindExample.tsx
  src/components/ModalSendRemindExample/index.scss
  src/components/ReadOnlyPlan/ReadOnlyPlan.tsx
  src/components/RemindItem/WritableRemindItem/WritableRemindItem.tsx
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/index.scss
  src/components/index.ts
  src/constants/api.ts
  src/hooks/apis/usePostRemindTest.ts
  src/hooks/useWritablePlan.ts
  src/styles/webkit.scss
  src/types/IconName.ts
Labels: 🍐배포

#437 [혜수] - 네비게이션 잘못 들어간 코드 삭제
  src/app/_components/Navigation/Navigation.tsx
Labels: 🚨긴급

#439 [혜수] - 피드백 스크롤 다른 페이지보다 얇은 문제 해결
  src/app/feedback/[planId]/_components/index.scss
Labels: 🎶낮음

#442 [노철] - 스크롤 위치 수정
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
Labels: 🚨긴급, 🐛버그

#443 [노철]-태그 인풋 수정
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/index.scss
Labels: 🚨긴급, 🐛버그

#445 [전체] - 배포
  src/app/(header)/my/index.scss
  src/app/(header)/my/page.tsx
  src/app/(header)/plans/[planId]/index.scss
  src/app/(header)/plans/[planId]/page.tsx
  src/app/(header)/plans/edit/[planId]/index.scss
  src/app/(header)/plans/edit/[planId]/page.tsx
  src/app/_components/Navigation/Navigation.tsx
  src/app/feedback/[planId]/_components/index.scss
  src/components/TagInput/TagInput.tsx
  src/components/TagInput/index.scss
Labels: 🚨긴급, 🍐배포

#447 [혜수] - 피드백하기 nav에서 삭제
  src/app/_components/Navigation/Navigation.tsx
Labels: 💡중간

#450 [민우] - constants index 파일 정리 및 기타 파일 삭제
  src/app/(header)/reminds/[planId]/page.tsx
  src/components/CircleProgressBar/CircleProgressBar.tsx
  src/components/CircleProgressBar/index.scss
  src/components/CreatePlanContent/CreatePlanContent.tsx
  src/components/CreatePlanIcon/CreatePlanIcon.tsx
  src/components/CreatePlanRemindDate/CreatePlanRemindDate.tsx
  src/components/CreatePlanRemindMessage/CreatePlanRemindMessage.tsx
  src/constants/index.ts
Labels: 💡중간
